[package]
name = "state-managed"
version = "0.1.0"
authors = ["Noah <noah@coronasoftware.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yewtil = { path = "../../", features = ["state"]}
yew = { path = "../../../yew" }
wasm-bindgen = "0.2.64"
